import React from "react";
import Head from "next/head";
import Image from "next/image";
import Box from "@mui/material/Box";

import {
  Background,
  Container,
  PasswordHeader,
  PasswordBody,
} from "../src/styled/styled";
import { Title, Password, Slide, CharacterRow } from "../src/components";
import copyIcon from "../public/fa-regular_copy.svg";

export default function Home() {
  const [charValue, setCharValue] = React.useState(0);
  return (
    <Box sx={Background}>
      <Head>
        <title>Password Generator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Title />
      <Box sx={Container}>
        <PasswordHeader>
          <Password />
          <Box sx={{ cursor: "pointer" }}>
            <Image src={copyIcon} alt="Copy Icon" />
          </Box>
        </PasswordHeader>
        <PasswordBody>
          <CharacterRow charValue={charValue} />
          <Slide charValue={charValue} setCharValue={setCharValue} />
        </PasswordBody>
      </Box>
    </Box>
  );
}
