import React from "react";
import Head from "next/head";
import { Box, FormGroup } from "@mui/material";

import {
  Background,
  Container,
  PasswordHeader,
  PasswordBody,
} from "../src/styled/styled";
import {
  Title,
  Password,
  Slide,
  CharacterRow,
  FormRow,
  Strength,
  CopyIcon,
  GenerateButton,
} from "../src/components";

export default function Home() {
  const [charValue, setCharValue] = React.useState(0);

  return (
    <Box sx={Background}>
      <Head>
        <title>Password Generator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Title />
      <Box sx={Container}>
        <PasswordHeader>
          <Password />
          <CopyIcon />
        </PasswordHeader>
        <PasswordBody>
          <CharacterRow charValue={charValue} />
          <Slide charValue={charValue} setCharValue={setCharValue} />
          <FormGroup sx={{ width: "100%" }}>
            <FormRow value="Include Uppercase letters" />
            <FormRow value="Include Lowercase letters" />
            <FormRow value="Include Numbers" />
            <FormRow value="Include Symbols" />
          </FormGroup>
          <Strength />
          <GenerateButton />
        </PasswordBody>
      </Box>
    </Box>
  );
}
