import React from "react";
import Head from "next/head";
import { Box, FormGroup, useMediaQuery } from "@mui/material";

import {
  Background,
  Container,
  PasswordHeader,
  PasswordBody,
} from "../src/styled/styled";
import {
  Title,
  Password,
  Slide,
  CharacterRow,
  FormRow,
  Strength,
  CopyIcon,
  GenerateButton,
} from "../src/components";

export default function Home() {
  const [charValue, setCharValue] = React.useState(0);
  const [included, setIncluded] = React.useState([]);
  const mobile = useMediaQuery("(max-width:425px)");
  const handleIncludedChange = (e) => {
    const index = included.indexOf(e.target.value);
    if (index === -1) setIncluded([...included, e.target.value]);
    else setIncluded(included.filter((include) => include !== e.target.value));
  };

  return (
    <Box sx={Background}>
      <Head>
        <title>Password Generator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Title mobile={mobile} />
      <Box sx={Container}>
        <PasswordHeader>
          <Password mobile={mobile} />
          <CopyIcon mobile={mobile} />
        </PasswordHeader>
        <PasswordBody>
          <CharacterRow charValue={charValue} mobile={mobile} />
          <Slide charValue={charValue} setCharValue={setCharValue} />
          <FormGroup sx={{ width: "100%" }}>
            <FormRow
              value="Include Uppercase letters"
              included={included}
              handleIncludedChange={handleIncludedChange}
            />
            <FormRow
              value="Include Lowercase letters"
              included={included}
              handleIncludedChange={handleIncludedChange}
            />
            <FormRow
              value="Include Numbers"
              included={included}
              handleIncludedChange={handleIncludedChange}
            />
            <FormRow
              value="Include Symbols"
              included={included}
              handleIncludedChange={handleIncludedChange}
            />
          </FormGroup>
          <Strength mobile={mobile} />
          <GenerateButton />
        </PasswordBody>
      </Box>
    </Box>
  );
}